### PR TITLE
Requested changes fixing

### LINKED ISSUE #980: Add validation layer selection in the export module
[EDIT]
# Current situation
The validation layer can't be exported.

# Desired situation
Add the selection of the validation layer in the Export module

# Accepted if
[ ] Validation layer can be exported

### LINKED ISSUE #988: Update swiss_species Encoding results (Out of Scope)
## Description
The goal is to replace the Swiss Species Registry (SSR) csv with a SSR Checklist on ChecklistBank. Currently this SSR-Checklist is **not** ready/available.

In this issue the Swiss Species encoding step is being prepared: Update of specific fields.

## Desired
- Species outside of Switzerland are marked as 'Out Of Scope' (`swissSpeciesCenter`) (Solves #905 )

## Accepted if
No match in swiss_species_registry.csv
- [x] `taxonIdCH` remains empty
- [x] `acceptedNamedUsage` remains empty
- [x] `swissSpeciesRegistered` = false
- [x] `swissSpeciesRegisteredAt` remains empty
- [x] `swissSpeciesCenter` = 'Not registered'
- [x] Status: Encoded

Match in swiss_species_registry.csv AND countryCode != CH
- [x] `taxonIdCH` is being populated
- [x] `acceptedNamedUsage` is being populated
- [x] `swissSpeciesRegistered` = true
- [x] `swissSpeciesRegisteredAt` = now
- [x] `swissSpeciesCenter` = 'Out of Scope
- [x] Status: Encoded

Match in swiss_species_registry.csv AND countryCode = CH
- [x] `taxonIdCH` is being populated
- [x] `acceptedNamedUsage` is being populated
- [x] `swissSpeciesRegistered` = true
- [x] `swissSpeciesRegisteredAt` = now
- [x] `swissSpeciesCenter` = 'Data Center'
- [x] Status: Encoded

### LINKED ISSUE #992: Move Validation and Swiss Registry information to side panel
## Description
The Validation and Swiss Registry Information in the records list is not relevant for a big chunk of records. Therefore this information needs to be transferred to the side-panel.

## Changes
- Swiss Registry is removed from records list
- Validation Status is removed from records list
- Validation Status is displayed below Swiss Registry in the side panel
- Show Validation status when: Record is encoded AND Swiss Registry IS NOT 'Out Of Scope' OR 'Unknown' (=Validation Status is only valuable for registered Swiss records)

## Accepted if
- [x] Swiss Registry is not displayed in records list
- [x] Validation Status is not displayed in records list
- [x] Swiss Registry is displayed in side-panel
- [x] Validation Status is displayed in side-panel below Swiss Registry
- [x] Validation Status is only shown when a record is encoded and registered by a Swiss Registry
- [x] Validation Status is hidden when a record is not encoded
- [x] Validation Status is hidden when a record is not registered by a Swiss Registry (e.g. Out Of Scope or Unknown)
- [ ] Migration for Existing Status of Swiss Registry
- [ ] Migration for Existing Status of Validation Status

### PR DESCRIPTION
**Pull request by sidler92**
# Pull Request

## Description

- correctly show validation state badge (only show if encoded, and some other flags)
- validation export refactored and changed to only export only validated_record values (skip if no validation_record exists)
- change order of encoding steps (swiss species after geo encoding, because swiss species depends on country_code)

## Related Issue

fixes #988 
fixes #980 
fixes #992

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Refactoring (no functional changes)
- [ ] Performance improvement
- [x] Test update
- [ ] Build/CI update
- [ ] Other (please describe):

## License Compliance

- [x] My changes comply with the GNU AGPL-3.0 license requirements
- [x] If my changes involve network interaction, I've ensured users can access the corresponding source code

### CODE REVIEW

File: lib/data_aggregator_web/live/collection_live/record/index.ex [hunk 1]
```diff
@@ -538,7 +538,10 @@ defmodule DataAggregatorWeb.CollectionLive.Record.Index do
             <div class="mt-4 flex space-x-2 max-sm:hidden">
               <.encoding_state_badge state={@selected_record.state} tooltip={false} />
               <.publication_state_badge state={@selected_record.publication_status} tooltip={false} />
-              <%= unless @selected_record.encoded_record.oth_swiss_species_registered == false do %>
+              <%= if @selected_record.validation_status == :validated ||
```
Comment (cloedu87) [inline lib/data_aggregator_web/live/collection_live/record/index.ex]: nitpick:

eventually a little helper function would be nice to have this logic not repeated twice. if the logic would also be used in the backend it might be even better to have a calculation on the `Record` or `EncodedRecord` resource. but so far not necessary I guess..

**Review by cloedu87 — CHANGES_REQUESTED** [review]
nitpick found, else: 🥳

File: lib/data_aggregator_web/live/collection_live/record/index.ex (hunk 1 above)
Comment (sidler92) [reply lib/data_aggregator_web/live/collection_live/record/index.ex]: Only used in frontend, so did it with a helper :+1:

**Review by cloedu87 — APPROVED** [review]
🥳
